Buffered reader cursor
toitlang/toit pull request #1188
Opened 2022-11-11 14:28 UTC by erikcorry

2022-11-12 07:27 UTC, kasperl commented on lib/reader.toit
> +  cursor -> int:
Maybe consumed is a better name given the description? I could see the name 'cursor' being used to delimit both the consumed part but also the buffered part.

Is it easy to add some tests of this functionality?

2022-11-15 11:47 UTC, floitsch approved these changes
LGTM.

2022-11-15 11:47 UTC, floitsch commented on lib/expect.toit
> +    if expected != error:
This doesn't make sense to me.

If the caught exception is not equal to the `expected` we have a message that says that we got `null`?

I think this test was correctly testing whether `error` was null`. That said: given that an exception can be a boolean, making it an explicit `error == null` is clearly better.

Also: I wouldn't use the `--message` thingy anymore. Just `throw "Expected exception, but executed normally"` or so.

2022-11-15 11:47 UTC, floitsch commented on lib/expect.toit
> +  finally: | is_exception exception |
Now we would change the message from "Expected throw, got <null>" to "Expected throw with <...>, but was Expected throw, got <null>".

I think the `finally` clause should disappear.

2022-11-15 14:15 UTC, floitsch requested changes
The last commit introduced changes to `tls/session.toit`.
That was probably accidental.

2022-11-15 14:18 UTC, floitsch approved these changes
LGTM with the changes to session.toit reverted.

2022-11-15 14:40 UTC, merged